config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'hostellers' => 'static_pages#hostellers'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :sessions
  resources :complaints
  get 'performance' => 'static_pages#performance' 
  get 'gallery' => 'static_pages#gallery'
  get 'executive' => 'static_pages#executive'

end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  belongs_to :user
  default_scope -> { order(created_at: :desc) }

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { rollno.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_ROLL_REGEX = /\A[a-z][a-z]\d\d[db]\d\d\d\z/i
	validates :email, length: { maximum: 255 }
	validates :password, presence: true, length: { minimum: 6, maximum: 50}
	validates :rollno, presence: true, length: { minimum: 8, maximum: 8}, format: { with: VALID_ROLL_REGEX }, 
	          uniqueness: {  case_sensitive: false }
	has_secure_password
	has_many :complaints
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
	def new
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(rollno: params[:session][:rollno].downcase)
    if user && user.authenticate(params[:session][:password])
    	logger.info("Valid User Signed in")
    	log_in(user)
      redirect_to current_user
    else
    	logger.info( "Invalid User rejected login" )
    	render 'new'
    end	
  end

  def destroy
  	logger.info("User logged out")
    log_out(params[:id])
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def hostellers
	end 
	def performance
	end
	def gallery
	end
	def executive
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
  end

  def create
      @user = User.new(user_params)
      logger.info(@user.errors.full_messages)
      if @user.save
      	log_in @user
        render 'show'
      else
      	redirect_to root_url
      end   
  end

  def show
  	@user = User.find(params[:id])
  end

  def user_params
  	params.require(:user).permit(:name,:email,:password,:password_confirmation, :rollno, :hostel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def page_title(title="")
		base_title = "Sarayu"
		if title.empty?
			base_title
		else
			title + " - " + base_title
		end
	end
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	#Saves temperory cookies about the session in the browser
	def log_in(user)
		session[ :user_id ] = user.id
	end

	#Returns the instance of the current user
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	# Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out(id)
  	session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/complaints/new.html.erb
<% provide(:title, 'Add Complaint') %>
<h1>Complaint</h1>
<div class="row">
      <div class = "col-md-6 col-md-offset-3">
      <% @user = User.new %>
            <%= form_for(@complaint) do |f| %>
                  <%= f.label :content %>*
                  <%= f.text_field :content %>
                  <br><br>
                  <%= f.submit "Create Complaint", class: "btn btn-primary" %>
            <% end %>
      </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>Sarayu Webops</small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Sarayu", root_path, id: "logo", class: "navbar-brand" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home",   root_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
				<% if logged_in? %>
					<li><%= link_to "Logout", logout_path, :method => :delete %></li>
				<% else %>	
					<li><%= link_to "Login", login_path %></li>
				<% end %>	
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=  page_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<center><h1>Contact</h1></center> <br> <br>
<h4>Keerthana</h4>
<p>Sarayu Hostel</p>
<p>EP15B012</p>
<p>keerukeerthana8@gmail.com</p>
<p><b>Mobile:</b>9551127841</p>
<br><br>
<h4>Mythreyi</h4>
<p>Sarayu Hostel</p>
<p>MM15B022</p>
<p>mytibala@gmail.com</p>
<p><b>Mobile:</b>9626835877</p>

app/views/static_pages/executive.html.erb
<% provide(:title, "Executive Body") %>
<center><h1>Executive Body</h1></center> <br> <br>

<h3> General Secretary </h3>
<h4>Keerthana</h4>
<p>EP15B012</p>
<p>keerukeerthana8@gmail.com</p>
<p><b>Mobile:</b>9551127841</p>

<<<<<<< HEAD
<a href="/assets/1.pdf"> Manifesto </a>
=======
<a href="1.pdf"> Manifesto </a>
>>>>>>> 21d7cfa9dd7ba6cea17358fc07a6c05a05cd7521

<h3> Sports Secretary </h3>
<h4>Srilekha</h4>
<p>EP15B010</p>
<p>gandharisrilekha@gmail.com</p>
<p><b>Mobile:</b>9551127841</p>

<a href="/assets/2.pdf"> Manifesto </a>

<h3> Technical Affairs Secretary </h3>
<h4>Mythreyi</h4>
<p>MM15B022</p>
<p>mytibala@gmail.com</p>
<p><b>Mobile:</b>9626835877</p>

<a href="/assets/3.pdf"> Manifesto </a>

<h3> Literary Affairs Secretary </h3>
<h4>Mruthula</h4>
<p>CH15B053</p>
<p>abcdef@gmail.com</p>
<p><b>Mobile:</b>9551127841</p>

<a href="/assets/4.pdf"> Manifesto </a>

app/views/static_pages/gallery.html.erb
<% provide(:title, "Gallery") %>
<center><h1>Gallery</h1></center> <br> <br>

<img src="/assets/pic1.jpg" alt="Picture1" height="500" width="600"/>
<img src="/assets/pic2.jpg" alt="Picture2" height="500" width="600"/>
<img src="/assets/pic3.jpg" alt="Picture3" height="500" width="600"/>
<img src="/assets/pic4.jpg" alt="Picture4" height="500" width="600"/>
<img src="/assets/pic5.jpg" alt="Picture5" height="500" width="600"/>
<img src="/assets/pic6.jpg" alt="Picture6" height="500" width="600"/>
<img src="/assets/pic7.jpg" alt="Picture7" height="500" width="600"/>
<img src="/assets/pic8.jpg" alt="Picture8" height="500" width="600"/>
<img src="/assets/pic9.jpg" alt="Picture9" height="500" width="600"/>
<img src="/assets/pic10.jpg" alt="Picture10" height="500" width="600"/>

app/views/static_pages/home.html.erb
<h1>Sarayu Hostel</h1>
<% if logged_in?  %>
	<%= link_to "Gallery", gallery_path,class: "btn btn-lg btn-primary" %>
	<br><br>
	<%= link_to "Inter Hostel Events", performance_path,class: "btn btn-lg btn-primary" %>
	<br>
	<br>
	<%= link_to "Hostellers", hostellers_path,class: "btn btn-lg btn-primary" %>
	<br><br>
	<%= link_to "Executive Body", executive_path,class: "btn btn-lg btn-primary" %>
	<% else %>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
<% end %>	
<br><br>

app/views/static_pages/hostellers.html.erb
<% provide(:title, "Hostellers") %>
<center><h1>Hostellers</h1></center> <br> <br>
<table>
	<tr>
		<th> Name </th>
		<th> Room Number </th>
		<th> Roll Number </th>
	</tr>
	<tr>
		<td> Srilekha Gandhari </td>
		<td> 421 </td>
		<td> EP15B010 </td>
	</tr>
	<tr>
		<td> Namida Mohammed </td>
		<td> 421 </td>
		<td> EE15B010 </td>
	</tr>
	<tr>
		<td> Anuvetha Govindarajan </td>
		<td> 426 </td>
		<td> EP15B009 </td>
	</tr>
	<tr>
		<td> Niveda G </td>
		<td> 426 </td>
		<td> EP15B019 </td>
	</tr>
	<tr>
		<td> Anicha Reuban </td>
		<td> 428 </td>
		<td> MM15B002 </td>
	</tr>
	<tr>
		<td> Kavitha G </td>
		<td> 428 </td>
		<td> CS15B056 </td>
	</tr>
	<tr>
		<td> Sahana Ramnath </td>
		<td> 214 </td>
		<td> EE15B109 </td>
	</tr>
	<tr>
		<td> Anupama Sekar </td>
		<td> 419 </td>
		<td> EE15B009 </td>
	</tr>
	<tr>
		<td> Keerthana S </td>
		<td> 459 </td>
		<td> EP15B012 </td>
	</tr>
	<tr>
		<td> Mythreyi R </td>
		<td> 462 </td>
		<td> MM15B022 </td>
	</tr>
</table>

app/views/static_pages/performance.html.erb
<% provide(:title, "Performance") %>
<center><h1>Inter-Hostel Events</h1></center> <br> <br> <br><br>

<center><h3>TechSoc</h3></center> <br><br>

<h4> Autonomous Robotics </h4>
<p> The Freshies put infi fight and got placed First!!! Beating all other hostels! </p>
<br>
<h4> Reverse Coding </h4>
<p> Got some 3rd place! </p>

<br><br><br>

<center><h3>LitSoc</h3></center> <br> <br>

<h4> LitSoc Dramatics </h4>
<p> Over a month of rigorous practice and preparation didn't go in vain for the "Twinkly Helter-Skelter" team got placed First! Moreover, "Best Actor - Female" went to Ramya Vijayram from Sarayu!</p>
<br>
<h4> Choreo </h4>
<p> Two amazing dancers, Pearly and Sai Teja, grabbed two postions out of top three! Bringing loads of pride to Sarayu!</p>
<br>
<h4> Choreo Night</h4>
<p> Got placed 5th! Brilliant performance!</p>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>
<h1>Signup</h1>
<div class="row">
      <div class = "col-md-6 col-md-offset-3">
      <% @user = User.new %>
            <%= form_for(@user) do |f| %>
                  <%= f.label :name %>*
                  <%= f.text_field :name %>
                  <br><br>
                  <%= f.label :rollno %>*
                  <%= f.text_field :rollno %>
                  <br><br>
                  <%= f.label :password %>*
                  <%= f.password_field :password %>
                  <br><br>
                  <%= f.label :password_confirmation %>*
                  <%= f.password_field :password_confirmation %>
                  <br><br>
                  <%= f.label :email %>
                  <%= f.text_field :email %>
                  <br><br>
                  <%= f.label :hostel %>
                  <%= f.text_field :hostel %>
                  <br><br>
                  <%= f.submit "Create User", class: "btn btn-primary" %>
            <% end %>
      </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
	<%= @user.name %>
</h1>